/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LidarRouteImport } from './routes/lidar'
import { Route as AntennaRouteImport } from './routes/antenna'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminToursRouteImport } from './routes/admin/tours'
import { Route as AdminSimulateRouteImport } from './routes/admin/simulate'
import { Route as AdminPeopleRouteImport } from './routes/admin/people'
import { Route as AdminLidarItemsRouteImport } from './routes/admin/lidar-items'
import { Route as AdminApiRouteImport } from './routes/admin/api'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LidarRoute = LidarRouteImport.update({
  id: '/lidar',
  path: '/lidar',
  getParentRoute: () => rootRouteImport,
} as any)
const AntennaRoute = AntennaRouteImport.update({
  id: '/antenna',
  path: '/antenna',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSimulateRoute = AdminSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLidarItemsRoute = AdminLidarItemsRouteImport.update({
  id: '/lidar-items',
  path: '/lidar-items',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/antenna': typeof AntennaRoute
  '/lidar': typeof LidarRoute
  '/welcome': typeof WelcomeRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/lidar-items': typeof AdminLidarItemsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/simulate': typeof AdminSimulateRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antenna': typeof AntennaRoute
  '/lidar': typeof LidarRoute
  '/welcome': typeof WelcomeRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/lidar-items': typeof AdminLidarItemsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/simulate': typeof AdminSimulateRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/antenna': typeof AntennaRoute
  '/lidar': typeof LidarRoute
  '/welcome': typeof WelcomeRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/lidar-items': typeof AdminLidarItemsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/simulate': typeof AdminSimulateRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/antenna'
    | '/lidar'
    | '/welcome'
    | '/admin/api'
    | '/admin/lidar-items'
    | '/admin/people'
    | '/admin/simulate'
    | '/admin/tours'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antenna'
    | '/lidar'
    | '/welcome'
    | '/admin/api'
    | '/admin/lidar-items'
    | '/admin/people'
    | '/admin/simulate'
    | '/admin/tours'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/antenna'
    | '/lidar'
    | '/welcome'
    | '/admin/api'
    | '/admin/lidar-items'
    | '/admin/people'
    | '/admin/simulate'
    | '/admin/tours'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AntennaRoute: typeof AntennaRoute
  LidarRoute: typeof LidarRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidar': {
      id: '/lidar'
      path: '/lidar'
      fullPath: '/lidar'
      preLoaderRoute: typeof LidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antenna': {
      id: '/antenna'
      path: '/antenna'
      fullPath: '/antenna'
      preLoaderRoute: typeof AntennaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/simulate': {
      id: '/admin/simulate'
      path: '/simulate'
      fullPath: '/admin/simulate'
      preLoaderRoute: typeof AdminSimulateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lidar-items': {
      id: '/admin/lidar-items'
      path: '/lidar-items'
      fullPath: '/admin/lidar-items'
      preLoaderRoute: typeof AdminLidarItemsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApiRoute: typeof AdminApiRoute
  AdminLidarItemsRoute: typeof AdminLidarItemsRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminSimulateRoute: typeof AdminSimulateRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApiRoute: AdminApiRoute,
  AdminLidarItemsRoute: AdminLidarItemsRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminSimulateRoute: AdminSimulateRoute,
  AdminToursRoute: AdminToursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AntennaRoute: AntennaRoute,
  LidarRoute: LidarRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
