/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LidarRouteImport } from './routes/lidar'
import { Route as AntennaRouteImport } from './routes/antenna'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LidarRoute = LidarRouteImport.update({
  id: '/lidar',
  path: '/lidar',
  getParentRoute: () => rootRouteImport,
} as any)
const AntennaRoute = AntennaRouteImport.update({
  id: '/antenna',
  path: '/antenna',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antenna': typeof AntennaRoute
  '/lidar': typeof LidarRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antenna': typeof AntennaRoute
  '/lidar': typeof LidarRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antenna': typeof AntennaRoute
  '/lidar': typeof LidarRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/antenna' | '/lidar' | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/antenna' | '/lidar' | '/welcome'
  id: '__root__' | '/' | '/antenna' | '/lidar' | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntennaRoute: typeof AntennaRoute
  LidarRoute: typeof LidarRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidar': {
      id: '/lidar'
      path: '/lidar'
      fullPath: '/lidar'
      preLoaderRoute: typeof LidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antenna': {
      id: '/antenna'
      path: '/antenna'
      fullPath: '/antenna'
      preLoaderRoute: typeof AntennaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntennaRoute: AntennaRoute,
  LidarRoute: LidarRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
